---
title: "Data"
output: html_document
date: "2025-04-15"
---

Upload necessary packages
```{r}
library(tidyverse)
library(quantmod)
library(rvest)
```

Webscrape updated s&p symbols and make list
```{r}
link = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
page = read_html(link) #gives the html document from the source link

# html_nodes --> pulls out the elements we want to grab
# html_text --> makes into text
spsymbol_unclean1 = page %>%  html_nodes("#constituents tr > :nth-child(1)") %>% html_text()
# spsymbol_unclean1 <- gives "/n" at the end for paragraph break

spsymbol_unclean2 <- trimws(spsymbol_unclean1) #take out "/n"

spsymbol <- spsymbol_unclean2[-1] # this takes out the header from wikipedia 
 # final symbols of s&p 500 from wikipedia

set.seed(99)
spsymbol_sample <- sample(spsymbol, size = 40)
spsymbol_sample # random sample of 40 s&p 500 companies to analyze data 
```

Upload dividend and stock price data
```{r}

for (i in spsymbol_sample) {
  getSymbols(i, from = "01/01/1900")
} #gives the stock information

for (i in spsymbol_sample) {
  div <- getDividends(i, from = "1900-01-01")
  print(paste("Dividends for", i))
  print(div)
} # gives the dividend data


for (i in spsymbol_sample) {
  symbol <- getSymbols(i, from = "01/01/1900")
  div <- getDividends(i, from = "1900-01-01")
  merge(symbol, div)
}


merged_data <- list()

for (i in spsymbol_sample) {
  tryCatch({
    symbol_data <- getSymbols(i, from = "1900-01-01", auto.assign = FALSE)
    dividend_data <- getDividends(i, from = "1900-01-01", auto.assign = FALSE)
    
    merged_data[[i]] <- merge(symbol_data, dividend_data)
  }, error = function(e) {
    message(paste("Failed for", i, ":", e$message))
    merged_data[[i]] <- NULL
  })
}

names(merged_data)
```